FROM python:3.9-slim

ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONFAULTHANDLER 1

RUN apt update && \
    apt install -y git --no-install-recommends && \
    apt autoremove && \
    apt clean

RUN pip install pipenv tox devpi-client
RUN useradd --create-home test && \
    chown -R test /home/test

WORKDIR /home/test

USER test

COPY . .

RUN pipenv install --dev